'use client'

import './style.css';
import { useState, useEffect } from 'react';
import axios from 'axios';
import Link from "next/link";
import { useRouter } from 'next/navigation';

function Home() {
  const [name, setName] = useState('');
  const [isLoading, setIsLoading] = useState(true); // Add a loading state
  const router = useRouter();

  useEffect(() => {
    const userDataStoredString = sessionStorage.getItem('userData');
    if (userDataStoredString) {
      try {
        const userDataStored = JSON.parse(userDataStoredString);
        if (userDataStored && userDataStored.name) {
          setName(userDataStored.name);
        } else {
          console.error('Error: User data in session storage is invalid');
        }
      } catch (error) {
        console.error('Error parsing user data from session storage:', error);
      }
    } else {
      console.error('Error: User data not found in session storage');
    }
    setIsLoading(false); // Set loading to false after attempting to load user data
  }, []);

  useEffect(() => {
    if (!isLoading && name === '') { // Check if not loading and name is empty
      router.push('/');
    }
  }, [name, isLoading, router]); 

  return (
    <div className="content-main">
      <p>Welcome, {name}!</p>
      <div className="card-grid">
      <Link href={'home/doc'}>
        <article className="card">
           <div className="card-header">
              <div>
                <span><img src="dcp.png" alt="Document Controlling Process" /></span>
                <h3>Document Controlling Process</h3>
              </div>
            </div>
            <div className="card-body">
              <p>A system for managing, organizing, and tracking organizational documents to ensure version control, accessibility, and compliance with established procedures and standards.</p>
            </div>
          
        </article></Link>

        <Link href={'home/ia'}>
        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="audit.png" /></span>
              <h3>Internal Audit Report</h3>
            </div>
          </div>
          <div className="card-body">
            <p>A document generated by internal auditors summarizing findings and recommendations related to a company's operations, financial practices, and compliance.</p>
          </div>
        </article>
        </Link>

      <Link href={'home/qualityobject'}>
        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="goal.png" /></span>
              <h3>Quality Objectives</h3>
            </div>
          </div>
          <div className="card-body">
            <p>Specific, measurable goals set by an organization to ensure and improve high-quality standards in products, services, or processes.</p>
          </div>
        </article>
      </Link>
      <Link href={'home/qualitypolicy'}>
        
        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="QPC.png" /></span>
              <h3>Quality Policy Communication</h3>
            </div>
          </div>
          <div className="card-body">
            <p>The effective communication of an organization's commitment to maintaining high-quality standards in its products, services, and processes to employees and stakeholders.</p>
          </div>
        </article>
        </Link>
        <Link href={'home/cpa'}>
        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="cpa.png" /></span>
              <h3>CPA Forms & Log</h3>
            </div>
          </div>
          <div className="card-body">
            <p>Tools used in Certified Public Accountancy to record financial transactions, audit evidence, and maintain organized financial records.</p>
          </div>
        </article>
        </Link>
        
        <Link href="/home/mangementmeeting">
        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="mrm.png" /></span>
              <h3>Management Review Meeting</h3>
            </div>
          </div>
          <div className="card-body">
            <p>The process of organizing and updating records that prove an organization's compliance with certifications and standards. </p>
							 </div>
        </article>
        </Link>

  {/*   <article className="card">
  <div className="card-header">
        <div>
            <span><img src="5S & Compliance Non-conformity.png" /></span>
            <h3>Compliance Non-conformity</h3>
        </div>
    </div>
    <div className="card-body">
        <p>5S represents a workplace organization method, and compliance non-conformity pertains to violations of regulatory compliance standards within an organization.</p>			
    </div>
</article> */}

                  <Link href={'home/reviewofsystem'}>
        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="Review of Procedures, Policies & Process Flow Charts.png" /></span>
              <h3>Review Of System Documents</h3>
            </div>
          </div>
          <div className="card-body">
            <p>An in-depth evaluation of an organization's documented procedures, policies, and process flow charts to ensure they are current, effective, and aligned with organizational goals and industry standards.</p>
						</div>
        </article>
        </Link>
        <Link href={'home/ppm'}>
        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="review.png" /></span>
              <h3>Preproduction Process Meeting & Checklist</h3>
            </div>
          </div>
          <div className="card-body">
            <p>A meeting held before a project or production to plan and coordinate activities, accompanied by a checklist outlining tasks and requirements to ensure a successful launch.</p>
						</div>
        </article>
        </Link>
        <Link href={'home/supplier'}>
        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="9989903_rating_evaluation_grade_ranking_rate_icon.png" /></span>
              <h3>Supplier Evaluation</h3>
            </div>
          </div>
          <div className="card-body">
            <p>The systematic assessment of a company's suppliers, which includes rating their performance, quality, and reliability to make informed procurement decisions.</p>
						</div>
        </article>
        </Link>

        <Link href={'home/externaldoc'}>
        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="storage-of-documents-files.png" /></span>
              <h3>External Documents</h3>
            </div>
          </div>
          <div className="card-body">
            <p>Records and materials originating from external sources outside an organization, such as industry publications, regulations, or customer contracts.</p>
						</div>
        </article>
        </Link>
        <Link href={'home/TA'}>
        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="pngegg.png" /></span>
              <h3>Training & Awareness</h3>
            </div>
          </div>
          <div className="card-body">
            <p>The process of educating employees and stakeholders to enhance their knowledge, understanding, and skills related to topics like company policies, safety procedures, compliance requirements, or new technologies.</p>
						 </div>
        </article>
        </Link>
        <Link href={'home/mcr'}>
        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="Maintain Certifications Records.png" /></span>
              <h3>Maintain Certifications Records</h3>
            </div>
          </div>
          <div className="card-body">
          <p>The process of organizing and updating records that prove an organization's compliance with certifications and standards.
</p>
          </div>
        </article>
</Link>
      </div>
    </div>
  );
}; 

export default Home;
