'use client'

import './style.css';
import { useState, useEffect } from 'react';
import axios from 'axios';
import Link from "next/link";

function Home() {
  const [username, setUsername] = useState('');

  useEffect(() => {
    axios.get('http://localhost:3001/api/user', { withCredentials: true })
      .then((res) => {
        setUsername(res.data.user.username);
      })
      .catch((err) => {
        console.error('Error fetching user data:', err);
      });
  }, []);


  return (
    
    <div className="content-main">
      
      <p>Welcome, {username}!</p>
      <div className="card-grid">
        <article className="card">
          <Link href="file:///C:/Users/Lenovo/techno/displaypg.html" style={{ textDecoration: 'none', color: '#212121' }}>
            <div className="card-header">
              <div>
                <span><img src="dcp.png" alt="Document Controlling Process" /></span>
                <h3>Document Controlling Process</h3>
              </div>
            </div>
            <div className="card-body">
              <p>A system for managing, organizing, and tracking organizational documents to ensure version control, accessibility, and compliance with established procedures and standards.</p>
            </div>
          </Link>
        </article>

        <Link href={'home/audit'}>
        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="audit.png" /></span>
              <h3>Internal Audit Report</h3>
            </div>
          </div>
          <div className="card-body">
            <p>A document generated by internal auditors summarizing findings and recommendations related to a company's operations, financial practices, and compliance.</p>
          </div>
        </article>
        </Link>

      <Link href={'home/qualityobject'}>
        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="goal.png" /></span>
              <h3>Quality Objectives</h3>
            </div>
          </div>
          <div className="card-body">
            <p>Specific, measurable goals set by an organization to ensure and improve high-quality standards in products, services, or processes.</p>
          </div>
        </article>
      </Link>
      <Link href={'home/qualitypolicy'}>
        
        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="QPC.png" /></span>
              <h3>Quality Policy Communication</h3>
            </div>
          </div>
          <div className="card-body">
            <p>The effective communication of an organization's commitment to maintaining high-quality standards in its products, services, and processes to employees and stakeholders.</p>
          </div>
        </article>
        </Link>
        <Link href={'home/cpa'}>
        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="cpa.png" /></span>
              <h3>CPA Forms & Log</h3>
            </div>
          </div>
          <div className="card-body">
            <p>Tools used in Certified Public Accountancy to record financial transactions, audit evidence, and maintain organized financial records.</p>
          </div>
        </article>
        </Link>

        <Link href="/home/mangementmeeting">
        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="mrm.png" /></span>
              <h3>Management Review Meeting</h3>
            </div>
          </div>
          <div className="card-body">
            <p>The process of organizing and updating records that prove an organization's compliance with certifications and standards. </p>
							 </div>
        </article>
        </Link>

        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="5S & Compliance Non-conformity.png" /></span>
              <h3>Compliance Non-conformity</h3>
            </div>
          </div>
          <div className="card-body">
            <p>5S represents a workplace organization method, and compliance non-conformity pertains to violations of regulatory compliance standards within an organization.</p>			
					</div>
                  </article>

        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="Review of Procedures, Policies & Process Flow Charts.png" /></span>
              <h3>Review Of System Documents</h3>
            </div>
          </div>
          <div className="card-body">
            <p>An in-depth evaluation of an organization's documented procedures, policies, and process flow charts to ensure they are current, effective, and aligned with organizational goals and industry standards.</p>
						</div>
        </article>

        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="review.png" /></span>
              <h3>Preproduction Process Meeting & Checklist</h3>
            </div>
          </div>
          <div className="card-body">
            <p>A meeting held before a project or production to plan and coordinate activities, accompanied by a checklist outlining tasks and requirements to ensure a successful launch.</p>
						</div>
        </article>

        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="9989903_rating_evaluation_grade_ranking_rate_icon.png" /></span>
              <h3>Supplier Evaluation</h3>
            </div>
          </div>
          <div className="card-body">
            <p>The systematic assessment of a company's suppliers, which includes rating their performance, quality, and reliability to make informed procurement decisions.</p>
						</div>
        </article>

        <Link href={'home/externaldoc'}>
        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="storage-of-documents-files.png" /></span>
              <h3>External Documents</h3>
            </div>
          </div>
          <div className="card-body">
            <p>Records and materials originating from external sources outside an organization, such as industry publications, regulations, or customer contracts.</p>
						</div>
        </article>
        </Link>

        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="pngegg.png" /></span>
              <h3>Training & Awareness</h3>
            </div>
          </div>
          <div className="card-body">
            <p>The process of educating employees and stakeholders to enhance their knowledge, understanding, and skills related to topics like company policies, safety procedures, compliance requirements, or new technologies.</p>
						 </div>
        </article>
        <article className="card">
          <div className="card-header">
            <div>
              <span><img src="Maintain Certifications Records.png" /></span>
              <h3>Maintain Certifications Records</h3>
            </div>
          </div>
          <div className="card-body">
          <p>The process of organizing and updating records that prove an organization's compliance with certifications and standards.
</p>
          </div>
        </article>

      </div>
    </div>
  );
}; 

export default Home;
